services:
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: homeAutomation
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/data/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - db
    restart: always
networks:
  db:
    driver: bridge

volumes:
  db: